# Generated by Django 3.2.15 on 2023-02-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='dead_line',
            field=models.DateTimeField(null=True, verbose_name='Deadline'),
        ),
    ]
